// Haywire Data Layer
// Loads real news data from JSON files generated by the Python scrapers.
// Falls back gracefully when no data files are present (e.g., local dev without scrapers).

export interface Article {
  id: string;
  title: string;
  url: string;
  source: string;
  sourceType: 'reddit' | 'rss' | 'scrape';
  category: string;
  timestamp: string;
  score?: number;
  commentCount?: number;
  isFeatured: boolean;
  thumbnail?: string | null;
}

export interface CategoryData {
  name: string;
  slug: string;
  articles: Article[];
}

interface AllNewsData {
  date: string;
  updated_at: string;
  categories: CategoryData[];
}

// --- PHT Timezone Helpers ---
// All dates in Haywire use Philippine Time (UTC+8) for consistency.

const PHT_OFFSET_MS = 8 * 60 * 60 * 1000;

/** Get the current date in PHT as YYYY-MM-DD */
function getPHTDateString(d: Date = new Date()): string {
  const pht = new Date(d.getTime() + PHT_OFFSET_MS);
  return pht.toISOString().split('T')[0];
}

/** Get a Date's PHT date string from an ISO timestamp */
function articleDatePHT(isoString: string): string {
  try {
    const d = new Date(isoString);
    if (isNaN(d.getTime())) return '';
    return getPHTDateString(d);
  } catch {
    return '';
  }
}

// --- Data Loading ---

let _cachedData: CategoryData[] | null = null;

function loadAllNews(): CategoryData[] {
  if (_cachedData) return _cachedData;

  try {
    // Import the combined JSON file generated by the aggregator
    // Astro resolves this at build time
    const allNewsFiles = import.meta.glob<AllNewsData>('../data/all_news.json', { eager: true });
    const keys = Object.keys(allNewsFiles);
    if (keys.length > 0) {
      const data = allNewsFiles[keys[0]];
      if (data && data.categories && data.categories.length > 0) {
        _cachedData = data.categories;
        return _cachedData;
      }
    }
  } catch (e) {
    // Fall through to empty data
  }

  // Return empty categories if no data file exists
  _cachedData = [];
  return _cachedData;
}

// Category slug → display name mapping
const CATEGORY_MAP: Record<string, string> = {
  'world-news': 'World News',
  'ph-news': 'Philippine News',
  'technology': 'Technology',
  'sports': 'Sports',
  'science': 'Science',
  'health': 'Health',
  'politics': 'Politics',
  'entertainment': 'Entertainment',
  'esports': 'E-Sports',
  'memes': 'Memes',
};

const CATEGORY_ORDER = [
  'world-news', 'ph-news', 'politics', 'technology', 'sports',
  'science', 'health', 'entertainment', 'esports', 'memes',
];

function emptyCategory(slug: string): CategoryData {
  return {
    name: CATEGORY_MAP[slug] || slug,
    slug,
    articles: [],
  };
}

// --- Public API ---

export function loadCategory(slug: string): CategoryData {
  const all = loadAllNews();
  const found = all.find(c => c.slug === slug);
  return found || emptyCategory(slug);
}

export function loadAllCategories(): CategoryData[] {
  const all = loadAllNews();
  if (all.length > 0) return all;

  // Return empty categories in the correct order
  return CATEGORY_ORDER.map(slug => emptyCategory(slug));
}

/** Load categories for a specific archive date (YYYY-MM-DD in PHT).
 *  Filters articles from the main dataset by their timestamp's PHT date.
 */
export function loadArchiveCategories(date: string): CategoryData[] {
  const all = loadAllNews();
  if (all.length === 0) {
    return CATEGORY_ORDER.map(slug => emptyCategory(slug));
  }

  // Filter each category's articles to only those published on the given date (PHT)
  const filtered: CategoryData[] = all.map(cat => {
    const dateArticles = cat.articles.filter(a => articleDatePHT(a.timestamp) === date);

    // Re-mark the first article as featured if there are results
    const articles = dateArticles.map((a, i) => ({
      ...a,
      isFeatured: i === 0,
    }));

    return {
      name: cat.name,
      slug: cat.slug,
      articles,
    };
  });

  // Only return categories that have articles for that date
  const withArticles = filtered.filter(c => c.articles.length > 0);
  return withArticles.length > 0 ? withArticles : filtered;
}

// --- Format Helpers ---

export function formatTimestamp(isoString: string): string {
  try {
    const d = new Date(isoString);
    if (isNaN(d.getTime())) return isoString;

    // Format in PHT (Asia/Manila)
    const options: Intl.DateTimeFormatOptions = {
      timeZone: 'Asia/Manila',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    };

    const formatted = new Intl.DateTimeFormat('en-US', options).format(d);
    // "September 27, 2026, 6:30 PM" → "September 27, 2026 | 6:30 PM"
    return formatted.replace(/,([^,]*)$/, ' |$1');
  } catch {
    return isoString;
  }
}

export function getCurrentDate(): string {
  const options: Intl.DateTimeFormatOptions = {
    timeZone: 'Asia/Manila',
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  };
  return new Intl.DateTimeFormat('en-US', options).format(new Date());
}

export function getCurrentTime(): string {
  const options: Intl.DateTimeFormatOptions = {
    timeZone: 'Asia/Manila',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  };
  return new Intl.DateTimeFormat('en-US', options).format(new Date());
}

export function getDateLabels(): { label: string; slug: string; isToday: boolean }[] {
  const labels = [];
  const now = new Date();

  for (let i = 0; i <= 7; i++) {
    const d = new Date(now.getTime() - i * 86400000);
    // Use PHT date consistently
    const slug = getPHTDateString(d);
    let label: string;
    if (i === 0) label = 'Today';
    else if (i === 1) label = 'Yesterday';
    else {
      const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
      // Get month/day in PHT
      const pht = new Date(d.getTime() + PHT_OFFSET_MS);
      label = `${months[pht.getUTCMonth()]} ${pht.getUTCDate()}`;
    }
    labels.push({ label, slug, isToday: i === 0 });
  }
  return labels;
}

