// Haywire Data Layer
// Loads real news data from JSON files generated by the Python scrapers.
// Falls back gracefully when no data files are present (e.g., local dev without scrapers).

export interface Article {
  id: string;
  title: string;
  url: string;
  source: string;
  sourceType: 'reddit' | 'rss' | 'scrape';
  category: string;
  timestamp: string;
  score?: number;
  commentCount?: number;
  isFeatured: boolean;
  thumbnail?: string | null;
}

export interface CategoryData {
  name: string;
  slug: string;
  articles: Article[];
}

interface AllNewsData {
  date: string;
  updated_at: string;
  categories: CategoryData[];
}

// --- Data Loading ---

let _cachedData: CategoryData[] | null = null;

function loadAllNews(): CategoryData[] {
  if (_cachedData) return _cachedData;

  try {
    // Import the combined JSON file generated by the aggregator
    // Astro resolves this at build time
    const allNewsFiles = import.meta.glob<AllNewsData>('../data/all_news.json', { eager: true });
    const keys = Object.keys(allNewsFiles);
    if (keys.length > 0) {
      const data = allNewsFiles[keys[0]];
      if (data && data.categories && data.categories.length > 0) {
        _cachedData = data.categories;
        return _cachedData;
      }
    }
  } catch (e) {
    // Fall through to empty data
  }

  // Return empty categories if no data file exists
  _cachedData = [];
  return _cachedData;
}

// Category slug → display name mapping
const CATEGORY_MAP: Record<string, string> = {
  'world-news': 'World News',
  'ph-news': 'Philippine News',
  'technology': 'Technology',
  'sports': 'Sports',
  'science': 'Science',
  'health': 'Health',
  'politics': 'Politics',
  'entertainment': 'Entertainment',
  'esports': 'E-Sports',
  'memes': 'Memes',
};

const CATEGORY_ORDER = [
  'world-news', 'ph-news', 'politics', 'technology', 'sports',
  'science', 'health', 'entertainment', 'esports', 'memes',
];

function emptyCategory(slug: string): CategoryData {
  return {
    name: CATEGORY_MAP[slug] || slug,
    slug,
    articles: [],
  };
}

// --- Public API ---

export function loadCategory(slug: string): CategoryData {
  const all = loadAllNews();
  const found = all.find(c => c.slug === slug);
  return found || emptyCategory(slug);
}

export function loadAllCategories(): CategoryData[] {
  const all = loadAllNews();
  if (all.length > 0) return all;

  // Return empty categories in the correct order
  return CATEGORY_ORDER.map(slug => emptyCategory(slug));
}

/** Load categories for a specific archive date */
export function loadArchiveCategories(date: string): CategoryData[] {
  // Try to load date-specific data
  try {
    const dateFiles = import.meta.glob<{ default: CategoryData }>('../data/archive/*/all_news.json', { eager: true });
    const key = Object.keys(dateFiles).find(k => k.includes(date));
    if (key) {
      const data = dateFiles[key] as unknown as AllNewsData;
      if (data && data.categories) return data.categories;
    }
  } catch (e) {
    // Fall through
  }

  // Fall back to current data (same behavior as before for now)
  return loadAllCategories();
}

// --- Format Helpers ---

export function formatTimestamp(isoString: string): string {
  try {
    const d = new Date(isoString);
    if (isNaN(d.getTime())) return isoString;

    const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    const month = months[d.getMonth()];
    const day = d.getDate();
    const year = d.getFullYear();
    let hours = d.getHours();
    const ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12 || 12;
    const mins = d.getMinutes().toString().padStart(2, '0');
    return `${month} ${day}, ${year} | ${hours}:${mins} ${ampm}`;
  } catch {
    return isoString;
  }
}

export function getCurrentDate(): string {
  const d = new Date();
  const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  return `${days[d.getDay()]}, ${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
}

export function getCurrentTime(): string {
  const d = new Date();
  let h = d.getHours();
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12 || 12;
  const m = d.getMinutes().toString().padStart(2, '0');
  return `${h}:${m} ${ampm}`;
}

export function getDateLabels(): { label: string; slug: string; isToday: boolean }[] {
  const labels = [];
  for (let i = 0; i <= 7; i++) {
    const d = new Date(Date.now() - i * 86400000);
    const slug = d.toISOString().split('T')[0];
    let label: string;
    if (i === 0) label = 'Today';
    else if (i === 1) label = 'Yesterday';
    else {
      const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
      label = `${months[d.getMonth()]} ${d.getDate()}`;
    }
    labels.push({ label, slug, isToday: i === 0 });
  }
  return labels;
}
